[package]
name = "my-php-rs-ext"
version = "0.1.0"
edition = "2021"

[dependencies]
ext-php-rs = "*"
reqwest = { version = "0.11.13", features = ["blocking", "cookies"] }

[lib]
crate-type = ["cdylib"]
