[package]
name = "reqwest"
version = "0.1.0"
edition = "2021"

[dependencies]
ext-php-rs = "0.10.0"
reqwest = { version = "0.11.13", default-features = false, features = ["blocking", "rustls-tls"] }
once_cell = "1.16.0"

[lib]
crate-type = ["cdylib"]
