services:
  php-fpm:
    #image: php:8.2-zts-alpine3.17
    image: php:8.1-zts-alpine3.17
    #build:
    #  dockerfile: Dockerfile
    #  context: .
    tty: true
    volumes:
      - php-sock:/run/php/php8.1-fpm.sock
      - ./:/var/www/app
      #- ./docker/php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
    working_dir: /var/www/app

  nginx:
    image: nginx:1.23.0
    ports:
      - 8088:80
    volumes:
      - php-sock:/run/php/php8.1-fpm.sock
      - .:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  php-sock: ~
